repos:
  # Preconditions
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.2.0
    hooks:
      - id: sync_with_poetry
        fail_fast: true
        args:
          - --db=poetry_to_pre_commit_mapping.json
  - repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps
        fail_fast: true

  # Language agnostic formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args:
          - --autofix
          - --trailing-commas
          - --no-sort
        exclude: poetry.lock
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args:
          - --wrap=80

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # Python
  ## Fixers
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [python]
        exclude: conftest.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-unused-variables
        require_serial: true
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8==7.2.0
          - flake8-2020
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-encodings
          - flake8-implicit-str-concat
          - flake8-new-union-types
          - flake8-pep585
          - flake8-simplify
          - flake8-tidy-imports
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-2020
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-encodings
          - flake8-implicit-str-concat
          - flake8-new-union-types
          - flake8-pep585
          - flake8-simplify
          - flake8-tidy-imports
  ## Formatters
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==25.1.0
  ## Linters
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-aiofiles
          - types-python-dateutil
          - types-requests
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          - --rcfile=.pylintrc
